### ISSUE TITLE
pcs.pah.kr

### ISSUE THREAD

**Issue by gunggme** [ParkMini/SW.AI-BusanHackaton#1]
how to use this?

**Comment by ParkMini** [comment]
No Problem.

**Comment by gunggme** [comment]
do not this working

**Comment by ParkMini** [comment]
It's work on My Computer

**Comment by gunggme** [comment]
my computer dos not working

**Comment by ParkMini** [comment]
Don't Worry
It's work on My Computer
If you have a Problem. Please Use Windows Trouble Shooter

**Comment by gunggme** [comment]
that's dos not working!! pls solve

**Comment by ParkMini** [comment]
You Using Linux or MacOS?
Linux and MacOS is not Support Windows Troubleshooter
pls use Windows 11 x86, Maybe Solved This problem

**Comment by gunggme** [comment]
ok that's solving  thangkyou

**Comment by ParkMini** [comment]
We Fixed this problem.
We will close this Issues
