### ISSUE TITLE
is doesn't working this program

### ISSUE THREAD

**Issue by gunggme** [ParkMini/SW.AI-BusanHackaton#3]
help me this issue

**Comment by CSeungJoo** [comment]
use chat-gpt

**Comment by ParkMini** [comment]
Ok. Don't Worry. My Windows TrobleShooter Will Help You Later.

**Comment by CSeungJoo** [comment]
close

**Comment by gunggme** [comment]
my OS is "Linux" does not working "Windows TrobleShooter"

**Comment by CSeungJoo** [comment]
use hyper-H

**Comment by gunggme** [comment]
what is vyper-H?

**Comment by gunggme** [comment]
Ok solved it Thk
